version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-db_sosm}
      MYSQL_USER: ${DB_USER:-sosmUser}
      MYSQL_PASSWORD: ${DB_PASS:-sosm_pass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-rootpass}
    volumes:
      - dbdata:/var/lib/mysql
      # Auto-init: runs .sql files once on a NEW volume (first startup)
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-p${DB_ROOT_PASS:-rootpass}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./www
      dockerfile: Dockerfile
    env_file: .env
    environment:
      # harden defaults in case .env is missing
      DB_HOST: db
      DB_NAME: ${DB_NAME:-db_sosm}
      DB_USER: ${DB_USER:-sosmUser}
      DB_PASS: ${DB_PASS:-sosm_pass}
      DB_PORT: ${DB_PORT:-3306}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-3000}:3000"

  # Optional: web DB UI at http://localhost:8080
  adminer:
    image: adminer
    depends_on: [db]
    ports: ["8080:8080"]

volumes:
  dbdata: {}
