#!/bin/bash

# move to script directory for relative references to be correct
cd $(dirname $(readlink -f $0))

NODEX=nothing

if `which nodejs > /dev/null 2>&1`; then
  echo using nodejs exe
  NODEX="nodejs"
elif `which node > /dev/null 2>&1`; then
  echo using node exe
  NODEX="node"
else
  echo "No nodejs executable found."
  exit 1
fi
DBM="../www/node_modules/db-migrate/bin/db-migrate"

echo "executing \"${NODEX} ${DBM} $@\""
NODE_PATH=../www/node_modules ${NODEX} ${DBM} $@
